version: '3.8'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # server:
  #   depends_on:
  #     - postgres
  #   build: .
  #   environment:
  #     - DATABASE_URL=postgresql://myuser:mypassword@postgres:5432/mydb?schema=public
  #     - DIRECT_URL=postgresql://myuser:mypassword@postgres:5432/mydb?schema=public
  #     - JUNZIORXIAOREN=---
  #   ports:
  #     - '3000:3000'

volumes:
  postgres: